#
# COPYRIGHT Ericsson 2020
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

apiVersion: v1
data:
  application.properties: |
    management.endpoint.metrics.enabled=true
    management.endpoints.web.exposure.include=*
    management.endpoint.prometheus.enabled=true
    management.metrics.export.prometheus.enabled=true
    management.metrics.web.server.auto-time-requests=true
kind: ConfigMap
metadata:
  name: {{ include "eric-oss-eniq-feature-installer.name" . }}-configmap
  labels:
{{ include "eric-oss-eniq-feature-installer.labels" . | indent 4 }}
  annotations:
{{ include "eric-oss-eniq-feature-installer.product-info" . | indent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "eric-oss-eniq-feature-installer.fullname" . }}
  labels:
    {{- include "eric-oss-eniq-feature-installer.labels" . | nindent 4 }}
  annotations:
   {{ include "eric-oss-eniq-feature-installer.product-info" . | indent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "eric-oss-eniq-feature-installer.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  strategy:
    type: {{ .Values.updateStrategy.type }}
    {{- if and (eq .Values.updateStrategy.type "RollingUpdate") .Values.updateStrategy.rollingUpdate }}
    rollingUpdate:
      maxUnavailable: {{ .Values.updateStrategy.rollingUpdate.maxUnavailable }}
      maxSurge: {{ .Values.updateStrategy.rollingUpdate.maxSurge }}
    {{- end }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "eric-oss-eniq-feature-installer.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/version: {{ include "eric-oss-eniq-feature-installer.version" . }}
      annotations:
        prometheus.io/path: "{{ .Values.prometheus.path }}"
        prometheus.io/port: "{{ .Values.service.port }}"
        prometheus.io/scrape: "{{ .Values.prometheus.scrape }}"
{{ include "eric-oss-eniq-feature-installer.product-info" . | indent 8 }}
{{- include "eric-oss-eniq-feature-installer.config-annotations" . | indent 8 }}
    spec:
      {{- if include "eric-oss-eniq-feature-installer.pullSecrets" . }}
      imagePullSecrets:
        - name: {{ template "eric-oss-eniq-feature-installer.pullSecrets" . }}
      {{- end }}
      serviceAccountName: {{ include "eric-oss-eniq-feature-installer.serviceAccountName" . }}
      securityContext:
        fsGroup: {{ include "eric-oss-eniq-feature-installer.fsGroup.coordinated" . }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "eric-oss-eniq-feature-installer.name" . }}-configmap
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ template "eric-oss-eniq-feature-installer.registryUrl" . }}/{{ template "eric-oss-eniq-feature-installer.repoPath" . }}{{ .Values.images.chassis.name }}:{{ .Values.images.chassis.tag }}"
          imagePullPolicy: {{ .Values.imageCredentials.pullPolicy }}
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            capabilities:
              drop:
              - all
          volumeMounts:
            - name: config-volume
              mountPath: /config
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 60 # Added initialDelaySeconds as the application is taking to come up
            httpGet:
              path: /actuator/health
              port: http
          readinessProbe:
            initialDelaySeconds: 60 # Added initialDelaySeconds as the application is taking to come up
            httpGet:
              path: /actuator/health
              port: http
          env:
          - name: TZ
            value: {{ template "eric-oss-eniq-feature-installer.timezone" . }}
      {{- if .Values.global }}
        {{- if .Values.global.security }}
          {{- if .Values.global.security.tls }}
            {{- if .Values.global.security.tls.enabled }}
          - name: CONNECT_MODE
            value: "tls"
            {{- if (eq .Values.service.endpoints.chassisapi.tls.enforced "required") }}
          - name: TLS_MODE
            value: "only_tls"
            {{- if (eq .Values.service.endpoints.chassisapi.tls.verifyClientCertificate "required") }}
          - name: TLS_CA
            value: "ca_path"
            {{- end }}
            {{- end }}
            {{- end }}
          {{- end }}
        {{- end }}
      {{- end }}
        {{- with index .Values "resources" }}
          resources:
            {{- toYaml . | nindent 12 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if eq .Values.affinity.podAntiAffinity "hard" }}
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
              matchExpressions:
                - key: app
                  operator: In
                  values:
                    - {{ template "eric-oss-eniq-feature-installer.name" . }}
              topologyKey: "kubernetes.io/hostname"
      {{- else if eq .Values.affinity.podAntiAffinity  "soft" }}
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - {{ template "eric-oss-eniq-feature-installer.name" . }}
                topologyKey: "kubernetes.io/hostname"
      {{- end }}