#
# COPYRIGHT Ericsson 2020
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "eric-oss-eniq-feature-installer.serviceAccountName" . }}
  labels:
{{- include "eric-oss-eniq-feature-installer.labels" . | nindent 4 }}
  annotations:
{{ include "eric-oss-eniq-feature-installer.product-info" . | indent 4 }}
{{- include "eric-oss-eniq-feature-installer.config-annotations" . | indent 4 }}
{{- end }}
