#
# COPYRIGHT Ericsson 2020
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

apiVersion: v1
kind: Service
metadata:
  name: {{ include "eric-oss-eniq-feature-installer.fullname" . }}
  labels:
{{ include "eric-oss-eniq-feature-installer.labels" . | indent 4 }}
  annotations:
    prometheus.io/path: "{{ .Values.prometheus.path }}"
    prometheus.io/port: "{{ .Values.service.port }}"
    prometheus.io/scrape: "{{ .Values.prometheus.scrape }}"
{{ include "eric-oss-eniq-feature-installer.product-info" . | indent 4 }}
{{- include "eric-oss-eniq-feature-installer.config-annotations" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "eric-oss-eniq-feature-installer.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
