nmapConfig:
  services:
    - name: "eric-oss-eniq-feature-installer"
      protocol:
        - "tcp"
        - "udp"
        - "sctp"
      additionalParams:
        - "-v"
        - "-p T:0-65535,U:1-1024,S:1-1024"
        - "--stats-every 30"
  reportDir : "nmap_reports_all"
